Traceback (most recent call last):
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jqbon\anaconda3\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
CS = np.array([0, 0.001, 0.002, 0.005, 0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2, 5]) #mmol/L
rate = np.array([0, 0.017537467, 0.030941975, 0.080327165, 0.1643835, 0.26569368, 0.745442547, 1.295792328, 2.419014706, 4.0402125, 5.534947297, 5.127217742, 7.074911496]) #mmol/L/min
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[1], line 1[0m
[1;32m----> 1[0m CS [38;5;241m=[39m np[38;5;241m.[39marray([[38;5;241m0[39m, [38;5;241m0.001[39m, [38;5;241m0.002[39m, [38;5;241m0.005[39m, [38;5;241m0.01[39m, [38;5;241m0.02[39m, [38;5;241m0.05[39m, [38;5;241m0.1[39m, [38;5;241m0.2[39m, [38;5;241m0.5[39m, [38;5;241m1[39m, [38;5;241m2[39m, [38;5;241m5[39m]) [38;5;66;03m#mmol/L[39;00m
[0;32m      2[0m rate [38;5;241m=[39m np[38;5;241m.[39marray([[38;5;241m0[39m, [38;5;241m0.017537467[39m, [38;5;241m0.030941975[39m, [38;5;241m0.080327165[39m, [38;5;241m0.1643835[39m, [38;5;241m0.26569368[39m, [38;5;241m0.745442547[39m, [38;5;241m1.295792328[39m, [38;5;241m2.419014706[39m, [38;5;241m4.0402125[39m, [38;5;241m5.534947297[39m, [38;5;241m5.127217742[39m, [38;5;241m7.074911496[39m])

[1;31mNameError[0m: name 'np' is not defined

