Traceback (most recent call last):
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\jqbond\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
test = 7         #An integer
# test = 7.0       #A floating point decimal
# test = True      #A boolean
# test = 4.75 + 3j #A complex number

iterable = test
for var in iterable:
    print(var)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_20840\4021572063.py[0m in [0;36m<cell line: 7>[1;34m()[0m
[0;32m      5[0m [1;33m[0m[0m
[0;32m      6[0m [0miterable[0m [1;33m=[0m [0mtest[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 7[1;33m [1;32mfor[0m [0mvar[0m [1;32min[0m [0miterable[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      8[0m     [0mprint[0m[1;33m([0m[0mvar[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mTypeError[0m: 'int' object is not iterable
TypeError: 'int' object is not iterable

