Traceback (most recent call last):
  File "C:\Users\Jesse Bond\AppData\Local\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Jesse Bond\AppData\Local\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Jesse Bond\AppData\Local\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Jesse Bond\AppData\Local\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Jesse Bond\AppData\Local\anaconda3\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Jesse Bond\AppData\Local\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Jesse Bond\AppData\Local\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Jesse Bond\AppData\Local\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
k     = 1
CAf   = 1
FAf   = 1
XA    = np.linspace(0.0, 0.9, 100) #Many fractional conversions
alpha = np.array([-2, -1, 0, 1, 2])#Many reaction orders
CA    = CAf*(1 - XA)
r     = k*CA**alpha
V     = FAf*XA/r
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
Cell [1;32mIn[5], line 7[0m
[0;32m      5[0m alpha [38;5;241m=[39m np[38;5;241m.[39marray([[38;5;241m-[39m[38;5;241m2[39m, [38;5;241m-[39m[38;5;241m1[39m, [38;5;241m0[39m, [38;5;241m1[39m, [38;5;241m2[39m])[38;5;66;03m#Many reaction orders[39;00m
[0;32m      6[0m CA    [38;5;241m=[39m CAf[38;5;241m*[39m([38;5;241m1[39m [38;5;241m-[39m XA)
[1;32m----> 7[0m r     [38;5;241m=[39m k[38;5;241m*[39m[43mCA[49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43malpha[49m
[0;32m      8[0m V     [38;5;241m=[39m FAf[38;5;241m*[39mXA[38;5;241m/[39mr

[1;31mValueError[0m: operands could not be broadcast together with shapes (100,) (5,) 
ValueError: operands could not be broadcast together with shapes (100,) (5,) 

